### ISSUE TITLE
Problem: report filters are not the same width and not aligned

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#140]
We could get a big usability win by attempting to align these UI elements a little more cleanly and consistently. 

Are we expecting any more filters? Are there other report management menu items we might want to add in the near future? 

<img width="1082" alt="Screen Shot 2021-06-04 at 1 29 45 PM" src="https://user-images.githubusercontent.com/672121/120859357-f12c8800-c538-11eb-8959-251e9211f5ec.png">

**Comment by tw4l** [comment]
@peterVG I don't know of additional filters that we're anticipating will be added in the near-term, though it's certainly possible.

As for alignment, ask and ye shall receive: https://github.com/artefactual-labs/AIPscan/pull/134/commits/f185711b3db64fe8fbda410d8549cd5a029376e8

I'm closing this in favour of futher discussion in the PR, as this issue is specific to that not-yet-merged work.
