### ISSUE TITLE
Generating report can take a long time

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#41]
Right now they are opened in a separate tab. The administrator needs to make sure that the server timeouts do not restrict the time needed to generate the reports. The users only sees a browser spinning wheel on the new tab to indicate that there is report generation activity. Perhaps this workflow can be made more user-friendly, e.g. when a report request is initiated, run the code needed to feed the report in a background job. Send a notification to the user when its ready. Only open and output to a new tab when the data is ready to be fed into the report.

**Comment by tw4l** [comment]
Refactoring of the reports in the previous months to rely on SQL queries for most of the business logic has resulted in much faster report generation. This should help, but the above-mentioned issues are still outstanding, particularly when reporting on very large Storage Services.

**Comment by mcantelon** [comment]
Report generation should be done asynchronously.

**Comment by mcantelon** [comment]
Possible rough implementation of moving report generation to Celery tasks:

* Add alert system based on user session
* Instead of opening a new tab, show an alert when a report has been requested
* Show some sort of "results" tab when past/present jobs exist for the user session
* An SQLlite DB table can be used to keep track of report tasks
* SQLlite columns to add to the table: report parameters, report type, user session ID, and results
* An SQLite TEXT field can be used to store report results (up to 2GB of data)

**Comment by mcantelon** [comment]
Another idea suggested is to look at using Elasticsearch to index fetch-derived data which seems like it could work.

**Comment by mcantelon** [comment]
Long-running reports have been changed to draw data from a Typesense index which should solve the speed issue (along with running AIPscan with MySQL as the primary data source).
