### ISSUE TITLE
Provide a 'Download METS' link from AIP view template

### ISSUE THREAD

**Issue by peterVG** [artefactual-labs/AIPscan#46]

**Comment by ross-spencer** [comment]
One thought about this @peterVG is that keeping more data in another place starts to become a bit of an information management problem. Even though we do have the METS, I wonder if it would be better to construct the METS URL and simply provide that back to the user? (Do we record it as the source in the database?) We have a couple of ways too where we could also prettyfy the URL for getting the METS so that AIPScan just becomes a router to get that information form the storage service as-is. 

That would free us up to clear-down the METS exports and keep the data we hold in AIPscan focused on the database where we have a larger number of options to clean that up - redact it etc.

**Comment by peterVG** [comment]
@ross-spencer yes, I like that approach. It was always my intention to add a task to clear out the local METS cache. I only thought of a new use for it off-the-cuff during the meeting discussion. However, I agree it's better housekeeping and avoiding an info mgt burden to clear them out and provide a dynamic link to METS download via the SS API.

**Comment by mcantelon** [comment]
Fixed merged (which proxies the METS data from the storage service).
